In [2]:
# Dependencies
import pandas as pd

In [3]:
# Read csv file with pandas and create dataframe
cancer_df = pd.read_csv("Resources/original_data/cancer_data.csv")
cancer_df

,Area,County,CancerType,Year,Sex,AgeAdjustedRate,CaseCount,Population
0,'Alabama','Shelby County','Lung and Bronchus','2013-2017','Male and Female','46.4','532','1044707'
1,'Alabama','Hale County','Lung and Bronchus','2013-2017','Male and Female','46.7','51','74956'
2,'Alabama','Monroe County','Lung and Bronchus','2013-2017','Male and Female','51.1','83','108662'
3,'Alabama','Coosa County','Lung and Bronchus','2013-2017','Male and Female','50.5','46','54815'
4,'Alabama','Perry County','Lung and Bronchus','2013-2017','Male and Female','49.4','34','48294'
...,...,...,...,...,...,...,...,...
2949,'Wyoming','Sublette County','Lung and Bronchus','2013-2017','Male and Female','Data Suppressed','Data Suppressed','50115'
2950,'Wyoming','Big Horn County','Lung and Bronchus','2013-2017','Male and Female','48.1','41','59560'
2951,'Wyoming','Sheridan County','Lung and Bronchus','2013-2017','Male and Female','41.1','89','149557'
2952,'Wyoming','Natrona County','Lung and Bronchus','2013-2017','Male and Female','53.3','242','405037'
2953,'Wyoming','Sweetwater County','Lung and Bronchus','2013-2017','Male and Female','44.3','89','222695'

In [4]:
#drop unnecessary columns
cancer_df = cancer_df.drop(columns = {'CancerType', 'Year', 'Sex', 'AgeAdjustedRate'})
cancer_df.head()

        Area           County CaseCount Population
0  'Alabama'  'Shelby County'     '532'  '1044707'
1  'Alabama'    'Hale County'      '51'    '74956'
2  'Alabama'  'Monroe County'      '83'   '108662'
3  'Alabama'   'Coosa County'      '46'    '54815'
4  'Alabama'   'Perry County'      '34'    '48294'

In [6]:
#rename columns to match other jupyter notebook df
renamed_cancer_df = cancer_df.rename(columns = {'Area': 'us_state', 'County': 'county'})
renamed_cancer_df.head()

    us_state           county CaseCount Population
0  'Alabama'  'Shelby County'     '532'  '1044707'
1  'Alabama'    'Hale County'      '51'    '74956'
2  'Alabama'  'Monroe County'      '83'   '108662'
3  'Alabama'   'Coosa County'      '46'    '54815'
4  'Alabama'   'Perry County'      '34'    '48294'