In [1]:
#import dependencies
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
import pandas as pd

In [3]:
#read csv and create initial DF
df = pd.read_csv('Resources/clean_data/combineddata.csv')
df.head()

,Unnamed: 0,us_state,county,days_with_aqi2019,good_days2019,moderate_days2019,unhealthy_sensitive_days2019,unhealthy_days2019,very_unhealthy_days2019,hazardous_days2019,...,average_hazardous_days,average_co_days,average_no2_days,average_ozone_days,average_so2_days,average_pm2_days,average_pm10_days,average_poverty_percentage,percent_pop_per_100k,cancer_classification
0,0,AL,Baldwin,271,237,34,0,0,0,0,...,0.0,0.0,0.0,215.25,0.0,57.25,0.0,10.4250,20.286986,medium
1,1,AL,Clay,107,97,10,0,0,0,0,...,0.0,0.0,0.0,0.00,0.0,112.75,0.0,17.8000,25.963561,medium
2,2,AL,Colbert,263,252,11,0,0,0,0,...,0.0,0.0,0.0,218.50,0.0,57.75,0.0,15.1250,19.761467,medium
3,3,AL,DeKalb,361,324,37,0,0,0,0,...,0.0,0.0,0.0,321.00,0.0,33.50,0.0,19.8750,15.357483,low
4,4,AL,Elmore,228,208,20,0,0,0,0,...,0.0,0.0,0.0,198.25,0.0,0.00,0.0,12.0275,16.158522,low

In [6]:
#keep average air quality, poverty, and classification columns
new_df = df[['average_good_days', 'average_moderate_days', 'average_unhealthy_sensitive_days', 'average_unhealthy_days',
            'average_very_unhealthy_days', 'average_hazardous_days', 'average_co_days', 'average_no2_days', 'average_ozone_days',
            'average_so2_days', 'average_pm2_days', 'average_pm10_days', 'average_poverty_percentage', 'cancer_classification']]


new_df

,average_good_days,average_moderate_days,average_unhealthy_sensitive_days,average_unhealthy_days,average_very_unhealthy_days,average_hazardous_days,average_co_days,average_no2_days,average_ozone_days,average_so2_days,average_pm2_days,average_pm10_days,average_poverty_percentage,cancer_classification
0,242.50,29.75,0.25,0.00,0.00,0.00,0.0,0.0,215.25,0.0,57.25,0.00,10.4250,medium
1,103.25,9.50,0.00,0.00,0.00,0.00,0.0,0.0,0.00,0.0,112.75,0.00,17.8000,medium
2,256.50,19.50,0.25,0.00,0.00,0.00,0.0,0.0,218.50,0.0,57.75,0.00,15.1250,medium
3,318.25,36.00,0.25,0.00,0.00,0.00,0.0,0.0,321.00,0.0,33.50,0.00,19.8750,low
4,184.75,13.50,0.00,0.00,0.00,0.00,0.0,0.0,198.25,0.0,0.00,0.00,12.0275,low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,256.00,104.25,4.25,0.75,0.00,0.00,0.0,0.0,350.25,0.0,14.50,0.50,6.8250,NaN
996,257.75,102.75,3.75,0.75,0.25,0.00,0.0,2.0,312.50,4.0,5.25,41.50,9.1275,low
997,310.50,54.25,0.50,0.00,0.00,0.00,0.0,0.0,347.75,0.0,16.75,0.75,6.3525,low
998,313.25,51.00,0.75,0.00,0.00,0.25,0.0,1.5,355.25,0.0,0.00,8.50,9.8275,low
999,328.50,36.50,0.25,0.00,0.00,0.00,0.0,0.0,334.75,29.0,1.50,0.00,10.9000,low

In [7]:
#drop rows with null values
clean_df = new_df.dropna()
clean_df

,average_good_days,average_moderate_days,average_unhealthy_sensitive_days,average_unhealthy_days,average_very_unhealthy_days,average_hazardous_days,average_co_days,average_no2_days,average_ozone_days,average_so2_days,average_pm2_days,average_pm10_days,average_poverty_percentage,cancer_classification
0,242.50,29.75,0.25,0.00,0.00,0.00,0.0,0.00,215.25,0.0,57.25,0.00,10.4250,medium
1,103.25,9.50,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.0,112.75,0.00,17.8000,medium
2,256.50,19.50,0.25,0.00,0.00,0.00,0.0,0.00,218.50,0.0,57.75,0.00,15.1250,medium
3,318.25,36.00,0.25,0.00,0.00,0.00,0.0,0.00,321.00,0.0,33.50,0.00,19.8750,low
4,184.75,13.50,0.00,0.00,0.00,0.00,0.0,0.00,198.25,0.0,0.00,0.00,12.0275,low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
994,294.25,69.00,1.75,0.25,0.00,0.00,0.0,0.25,294.25,0.0,43.25,27.50,8.8750,low
996,257.75,102.75,3.75,0.75,0.25,0.00,0.0,2.00,312.50,4.0,5.25,41.50,9.1275,low
997,310.50,54.25,0.50,0.00,0.00,0.00,0.0,0.00,347.75,0.0,16.75,0.75,6.3525,low
998,313.25,51.00,0.75,0.00,0.00,0.25,0.0,1.50,355.25,0.0,0.00,8.50,9.8275,low
999,328.50,36.50,0.25,0.00,0.00,0.00,0.0,0.00,334.75,29.0,1.50,0.00,10.9000,low

In [12]:
#set X and y
X = clean_df.drop('cancer_classification', axis=1)
y = clean_df['cancer_classification']

print(X.shape, y.shape)

(937, 13) (937,)